@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ0MTQyMjUzLCJleHAiOjE3NDQxNDM0NTN9.FosZvyczK8IqKHNtT123tUDOZN5QUbOE3_vlzwTHjsk

### AUTH

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Teste", 
  "email": "teste@email.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}

### TASKS

POST http://localhost:3000/api/tasks/create
Content-Type: application/json
Authorization: {{token}}

{
  "title": "New Task",
  "userId": 1
}

###

GET http://localhost:3000/api/tasks/read
Authorization: {{token}}

###

PUT http://localhost:3000/api/tasks/update/1
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Test Task"
}

###

DELETE http://localhost:3000/api/tasks/delete/8
Authorization: {{token}}

###
