@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6MSwiaWF0IjoxNzQzNzAxNzYyLCJleHAiOjE3NDM3MDI5NjJ9.88zTRsbuCWe5k5evfuUTel4qG1QeMPvf2dpzVOFdxro

### AUTH

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Teste", 
  "email": "teste@email.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}

### TASKS

POST http://localhost:3000/api/tasks/create
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Test Task",
  "userId": 1
}

###
