@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNzg5ODg4LCJleHAiOjE3NDM3OTEwODh9.QLmSlH2i8B2XQjbK5EsX64fLcBessKDVeo0-SiVYfNc

### AUTH

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Teste", 
  "email": "teste@email.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}

### TASKS

POST http://localhost:3000/api/tasks/create
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Test Task",
  "userId": 1
}

###

GET http://localhost:3000/api/tasks/get-all
Authorization: {{token}}

###
